sudo: required
services:
  - docker

before_install:
  - docker build -t harshil2612/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harshil2612/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-ca-central-1-428452235102"
  bucker_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"